<?xml version="1.0"?>
<package format="3">
  <name>ustb_doggo_urdf</name>
  <version>0.0.1</version>
  <description>USTB Doggo robot description</description>

  <maintainer email="you@example.com">Oakfox</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- 运行依赖 -->
  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  
  <!-- URDF相关 -->
  <exec_depend>robot_state_publisher</exec_depend>
  
  <!-- 控制相关（必须添加） -->
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>ros2_control</exec_depend>
  <exec_depend>ros2_controllers</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend>
  <exec_depend>velocity_controllers</exec_depend>
  <exec_depend>position_controllers</exec_depend>
  
  <!-- Gazebo相关 -->
  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>gazebo_ros2_control</exec_depend>
  
  <!-- 可视化 -->
  <exec_depend>rviz2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

